### ISSUE TITLE
"1k+" unread count

### ISSUE THREAD

**Issue by Nolanus** [alphamyd/meetfranz-recipe-feedly#1]
Feedly automatically truncates too large unread count numbers into something like "1k+".

The current implementation of getCount() would extract an unread count of "1" out of this. Unfortunately there's no way to determine the exact number of unread items in these situations (looping over category-items or subscriptions only works if they are expanded, as they get removed from the DOM in collapsed mode).

**Comment by alphamyd** [comment]
Hello @Nolanus 
Thanx for reporting.

There is one «little» problem, Franz API method [setBadge](https://github.com/meetfranz/plugins/blob/master/docs/frontend_api.md#user-content-setbadge) acept ONLY `int` values.

I try to contact Franz developer for more details.

**Comment by alphamyd** [comment]
No answer from developer, so i change code to understand «1k+» unread counts.
Now, if you have unread count more than «1k+» (or «**N**k+») it will be displayed like 1000 (or **N**000)
